version: "3.8"

services:
  node:
    build:
      context: ./
    container_name: node-service
    depends_on:
      - db
    volumes:
      - .:/app
    command: npm start
    ports:
      - 8080:8080
  db:
    image: postgres:14-alpine
    container_name: db-service
    restart: always
    environment:
      POSTGRES_DB: peoplenetwork
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
