version: "3.8"

services:
  db-dev:
    image: postgres:14-alpine
    container_name: db-dev
    restart: always
    environment:
      POSTGRES_DB: peoplenetwork
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
